version: '3.8'

services:
  api:
      build: .
      command: bash -c "python3 fixtures/configure_database.py && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py shell < fixtures/initSuperUser.py && python3 manage.py runserver 0.0.0.0:8000"
      volumes:
        - ./API:/usr/src/API/
      ports:
        - 80:8000
      depends_on:
        - db
      env_file:
        - ./.env.dev
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "superpassword"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5000:5432

volumes:
  postgres_data: